top5/config/routes.rb
Rails.application.routes.draw do
  # resources :movies
  # resources :users
  # resources :static_pages
  # resources :sessions

  root to: 'users#login'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'users#login'

  post '/signup' => 'users#new'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/edit' => 'users#edit'
  patch '/users/update' => 'users#update'

  # search field page
  get '/home' => 'movies#home'
  # search results
  post '/mresults' => 'movies#index'
  #show details of one movie in search
  get '/mresults/:imdbID' => 'movies#show'

  #get info on movie and add to database
  post '/create' => 'movies#create'
  post '/remove_from_top' => 'movies#remove_from_top'
  get '/showall' => 'movies#show_alltop5'
  get '/mytop5' => 'movies#my_top_5'

end

top5/app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  #lambda function for database manipulation
  scope :top_five, -> { where(:top5 => true) }

end

top5/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :movies

end

top5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/home' unless current_user
  end

end

top5/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

#############################################

  def remove_from_top
    # CHANGE TOP-5 BOOLEAN TO FALSE - REMOVES IT FROM LIST
    Movie.find(params[:id]).update(:top5 => false)
    redirect_to mytop5_path
    # flash[:message] = "."
  end

#############################################

  def index
    # passing user search input into API
    @results = HTTParty.get "http://www.omdbapi.com/?s=#{params[:searchterm]}"
    # grabing the unique movie code for show action
    @imdbID = @results['imdbID']

  end

#############################################

  def show
    # passing chosen movie code into API imdbID search
    @pick = HTTParty.get "http://www.omdbapi.com/?i=#{params[:imdbID]}"
  end

#############################################

  def create
  # checking "top-five" as defined in SCOPE (find this in movie.rb) stops users adding more than 5 movies
  if current_user.movies.top_five.length >= 5
    # if list is full flash message and do nothing
    flash[:message] = "YOUR TOP 5 LIST IS FULL! REMOVE SOME TO ADD MORE."
    redirect_to '/home'
    return
  elsif current_user.movies.top_five.length >= 4
    #this elsif tells the user not to add any more AFTER this one.

    # make a new request to omdb api to get the information from the movie again.
    @pick = HTTParty.get "http://www.omdbapi.com/?i=#{params[:id]}"
    movie = Movie.new
    movie.actors = @pick['Actors']
    movie.imgurl = @pick["Poster"]
    movie.director = @pick["Director"]
    movie.imdbID = @pick["imdbID"]
    # set top5 to true by default
    movie.top5 = true
    #associate the user
    movie.user_id = current_user.id
    flash[:message] = "YOUR LIST IS COMPLETE!"
    movie.save
    redirect_to '/home'
    return
  end

    # make a new request to omdb api to get the information from the movie again.
    @pick = HTTParty.get "http://www.omdbapi.com/?i=#{params[:id]}"
    movie = Movie.new
    movie.actors = @pick['Actors']
    movie.imgurl = @pick["Poster"]
    movie.director = @pick["Director"]
    movie.imdbID = @pick["imdbID"]

    # set top5 to true by default
    movie.top5 = true
    # associate the user
    movie.user_id = current_user.id

    movie.save
    if movie.save
      flash[:message] = "YOU HAVE ADDED TO YOUR TOP 5 FIVE... ADD SOME MORE!"
      redirect_to '/home'
    end
  end

#############################################

  def my_top_5
    # get current user and and pass it to the view
    @user = User.find(current_user.id)
  end

#############################################

  def show_alltop5
    @user = User.find(current_user.id)
    # CROSS DB stuff  - attaches the user with the movies that have top5 = true
    @top_movies = Movie.joins(:user).where(:top5 => true)
    # put them into a list associated with that user - via helper function
    @top_movies = @top_movies.group_by {|i| i.user.username }
  end

#############################################

  def user_movies
  end

#############################################

  def home
  end

#############################################

  def update
  end

#############################################

  def destroy
  end

#############################################

end

top5/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  #############################################

  def create
    user = User.find_by_email(params[:email])
    # If we find the user and the password matches
    if user && user.authenticate(params[:password])
      # saver the user id inside the browser cookie and log them in
      session[:user_id] = user.id
      redirect_to '/home'
    else
      flash[:error] = "your password is bad"
      redirect_to '/'
    end
  end

  #############################################

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  #############################################
  
end

top5/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

#############################################

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/home'
    else
      flash[:message] = "INCORRECT LOGIN TRY AGAIN..."
      # flash[:errors] = {'class' => 'errors', :errors => user.errors.full_messages}
      redirect_to '/signup'
    end
  end

  # a catch all for security and convenience
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  #############################################

  def login
  end

  #############################################

  def edit
  end

  #############################################

  def update
    current_user.update_attributes(user_params)
    flash[:message] = "YOUR UPDATED"
    redirect_to root_path
  end

  #############################################

end

top5/app/helpers/application_helper.rb
module ApplicationHelper
end

top5/app/helpers/movies_helper.rb
module MoviesHelper
end

top5/app/helpers/sessions_helper.rb
module SessionsHelper
end

top5/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

top5/app/helpers/users_helper.rb
module UsersHelper
end

top5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Top5</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,800,700italic,700,600italic,600,400italic,300italic,300,800italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Teko:400,700' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

top5/app/views/movies/home.html.erb
<div class="top-flex">
  <button class="btn-logout"><a href="/logout">LOGOUT</a></button>
  <p class="small-text"><a href="/users/edit">change your details</a></p>
</div>

<div class='header-area'>
  <% if current_user %>
    <div class="title-position">
      <!-- put user name in heading -->
      <h1><%= current_user.username.upcase %>'S <span>TOP 5 MOVIES<span></h1>
      <div><button class="btn-small"><a href="/showall">ALL TOP 5s</a></button></div>
    </div>
  <% end %>
</div>

<div class="frames">
    <div class='content-container'>
      <!-- SEARCH FIELD -->
      <%= form_tag mresults_path do %>
        <%= text_field_tag :searchterm, "", class: 'text-field', autofocus: true, placeholder: 'SEARCH' %>
        <%= submit_tag "SUBMIT", class: 'btn-large btn-thin' %>
      <% end %><br>

      <% if flash[:message] %>
        <div class="flash">
          <%= flash[:message]%>
        </div>
      <% end %>

    </div>
  <!-- USERS TOP 5 ROUTED TO RIGHT SIDE IFRAME -->
  <iframe class="iframe" src="/mytop5" width="160" height="1241" frameBorder="0" scrolling="no" frameBorder="0" bgcolor="#38322f"></iframe>

</div>

top5/app/views/movies/index.html.erb
<div class="top-flex">
  <button class="btn-logout"><a href="/logout">LOGOUT</a></button>
  <p class="small-text"><a href="/users/edit">change your details</a></p>
</div>

<div class='header-area'>
  <% if current_user %>
    <div class="title-position">
      <!-- put user name in heading -->
      <h1><%= current_user.username.upcase %>'S <span>TOP 5 MOVIES<span></h1>
      <div><button class="btn-small"><a href="/showall">ALL TOP 5s</a></button></div>
    </div>
  <% end %>
</div>

<div class="frames">
  <div class='content-container'>
    <%= form_tag mresults_path do %>
      <%= text_field_tag :searchterm, "", class: 'text-field', autofocus: true, placeholder: 'SEARCH' %>
      <%= submit_tag "SUBMIT", class: 'btn-large btn-thin' %><br>
    <% end %>

    <div class="search-layout">
      <!-- check if api result response is coming back empty to avoid error-->
    <% if @results.length > 2 %>
      <% @results["Search"].each do |put| %>
        <div class="movie-layout">
          <a href="/mresults/<%= put["imdbID"]%>">
            <img class='search-images' src= "<%= put["Poster"]%>"></a>
            <%= button_to "ADD", {:controller => 'movies', :action => 'create', :id => put["imdbID"] }, {class: 'btn-addto5' } %>
        </div>
        <% end %>
      <% else %>
          <div class="flash"><%= flash[:message] = "YOUR SEARCH RETURNED NO RESULTS..." %></div>
          <div class="flash l2"><%= flash[:message] = "TRY AGAIN!" %></div>
      <% end %>
    </div>
  </div>
  <!-- USERS TOP 5 ROUTED TO RIGHT SIDE IFRAME -->
  <iframe class="iframe" src="/mytop5" width="160" height="1241" frameBorder="0" scrolling="no" frameBorder="0"></iframe>
</div>

top5/app/views/movies/my_top_5.html.erb
<!-- THIS PAGE IS ROUTED TO RIGHT SIDE IFRAME -->
<div class="top-flex">
  <button class="btn-logout"><a href="/logout">LOGOUT</a></button>
  <p class="small-text"><a href="/users/edit">change your details</a></p>
</div>

<div class='header-area'>
  <% if current_user %>
    <div class="title-position">
      <!-- put user name in heading -->
      <h1><%= current_user.username.upcase %>'S <span>TOP 5 MOVIES<span></h1>
      <div><button class="btn-small"><a href="/showall">ALL TOP 5s</a></button></div>
    </div>
  <% end %>
</div>

<!-- list the movies that are in users top 5 -->
<div class="stretch">
  <div class='top5-list'>
    <div class="local-username">
      <%= @user.username.upcase %>'S<br />TOP 5 LIST
    </div>
    <% current_user.movies.where(:top5 => true).each do |put| %>
    <a href="/mresults/<%= put["imdbID"] %>"target="_top">
      <img class='top5-images' src="<%= put.imgurl %>">
    </a>
    <%= button_to "X", {:controller => 'movies', :action => 'remove_from_top', :id => put.id }, {class: 'btn-remove-from5' } %>
    <% end %>
  </div>
</div>

top5/app/views/movies/show.html.erb
<div class="top-flex">
  <button class="btn-logout"><a href="/logout">LOGOUT</a></button>
  <p class="small-text"><a href="/users/edit">change your details</a></p>
</div>

<div class='header-area'>
  <% if current_user %>
    <div class="title-position">
      <!-- put user name in heading -->
      <h1><%= current_user.username.upcase %>'S <span>TOP 5 MOVIES<span></h1>
      <div><button class="btn-small"><a href="/showall">ALL TOP 5s</a></button></div>
    </div>
  <% end %>
</div>

<div class='show-container'>
  <div>
    <!-- back to search option -->
    <div><button class="btn-small-showpage"><a href="/home">BACK TO SEARCH</a></button></div>
    <!-- add to top-5 options -->
    <%= button_to "ADD TO TOP 5", { :controller => 'movies', :action => 'create', :id => @pick["imdbID"] }, {class: 'btn-small-showpage' } %>
    </div>
    <!-- show large poster and details -->
  <div><img class="show-poster" src= "<%= @pick["Poster"]%>"></div>
    <div class='show-details'>
      <p>Title: <span><%= @pick["Title"] %></span></p>
      <p>Director: <span><%= @pick["Director"] %></span></p>
      <p>Year: <span><%= @pick["Year"] %></span></p>
      <p>Actors: <span><%= @pick["Actors"] %></span></p>
      <p>Plot: <span><%= @pick["Plot"] %></span></p>
      <p>Rating: <span><%= @pick["Rated"] %></span></p>
    </div>
  </div>
  <!-- USERS TOP 5 ROUTED TO RIGHT SIDE IFRAME -->
  <iframe class="iframe" src="/mytop5" width="160" height="1241" frameBorder="0" scrolling="no" frameBorder="0"></iframe>
</div>

top5/app/views/movies/show_alltop5.html.erb
<div class="top-flex">
  <button class="btn-logout"><a href="/logout">LOGOUT</a></button>
  <p class="small-text"><a href="/users/edit">change your details</a></p>
</div>

<div class='header-area'>
  <% if current_user %>
    <div class="title-position">
      <!-- put top 5 heading -->
      <h1><span>TOP 5 MOVIE LISTS<span></h1>
      <div><button class="btn-small"><a href="/home">BACK TO SEARCH</a></button></div>
    </div>
  <% end %>
</div>

<div class="frames">
  <!-- put background color behind the list -->
  <div class="stretch-users-global">
    <!-- display each list in a row -->
    <div class='top5-list-global'>
    <% @top_movies.each do |username, movie| %>
    <!-- display username and movie images in a column -->
    <div class="list-all-separately">
      <div class="global-username"><%= username.upcase %>'S<br /> TOP 5 MOVIES</div><br>
      <% movie.each do |put| %>
      <!-- pass unique code for show page on click -->
        <a href="/mresults/<%= put["imdbID"] %>">
          <!-- show movie poster images -->
        <img class='top5-images-global' src="<%= put.imgurl %>">
      <% end %>
      </div>
    <% end %>
  </div>
</div>
  <!-- USERS TOP 5 ROUTED TO RIGHT SIDE IFRAME -->
  <iframe class="iframe" src="/mytop5" width="160" height="1241" frameBorder="0" scrolling="no" frameBorder="0"></iframe>
</div>

top5/app/views/users/edit.html.erb
<h1>EDIT DETAILS</h1>

<div class="login-container">

  <%= form_for current_user, url: '/users/update' , method: :patch do |f| %>
    <%= f.text_field :email, class: 'text-field', autofocus: true, placeholder: 'chuck@norris.com' %><br />
    <%= f.text_field :username, class: 'text-field', autofocus: true, placeholder: 'CHUCKY' %><br />
    <%= f.password_field :password, class: 'text-field', autofocus: true, placeholder: 'PASSWORD' %><br />
    <%= f.password_field :password_confirmation, class: 'text-field', autofocus: true, placeholder: 'PASSWORD AGAIN' %><br />
    <%= f.submit 'SUBMIT', class: 'btn-large btn2'  %>
  <% end %>

</div>

top5/app/views/users/login.html.erb
<!-- background image added to give context to the app -->
<div class="home-background">

<h1><span>TOP 5 MOVIE LISTS</span>: LOGIN</h1>

<div class='login-container'>

  <% if flash[:message] %>
    <div class="flash"><%= flash[:message]%></div>
  <% end %>

  <%= form_tag login_path do %>
    <%= text_field_tag :email, "", class: 'text-field', autofocus: true, placeholder: 'chuck@norris.com' %><br>
    <%= password_field_tag :password, "", class: 'text-field', autofocus: true, placeholder: 'password'  %><br>
    <%= submit_tag "LOG IN", class: 'btn-large' %>
  <% end %>

  <h2>OR</h2>
  <%= button_to 'REGISTER', signup_path, class: 'btn-large btn2' %>

</div>

top5/app/views/users/new.html.erb
<!-- background image added to give context to the app -->
<div class="home-background reg">

  <h1>REGISTER PAGE</h1>

  <% if flash[:errors] %>
    <p><%= flash[:errors] %></p>
  <% end %>

  <div class="login-container">
    <%= form_for :user, url: '/users' do |f| %>
      <%= f.text_field :email, class: 'text-field', autofocus: true, placeholder: 'chuck@norris.com' %><br />
      <%= f.text_field :username, class: 'text-field', autofocus: true, placeholder: 'CHUCKY' %><br />
      <%= f.password_field :password, class: 'text-field', autofocus: true, placeholder: 'PASSWORD' %><br />
      <%= f.password_field :password_confirmation, class: 'text-field', autofocus: true, placeholder: 'PASSWORD AGAIN' %><br />
      <%= f.submit 'REGISTER', class: 'btn-large btn2'  %>
    <% end %>

    <h2>OR</h2>
    <%= button_to 'LOG IN', '/login', class: 'btn-large' %>

  </div>
</div>